<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'JvsLayout\Module'                            => __DIR__ . '/Module.php',
  'JvsLayout\EventListener\LayoutRouteListener' => __DIR__ . '/src/JvsLayout/EventListener/LayoutRouteListener.php',
);
